### ISSUE TITLE
Incompatibility with LCIO v02-06

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#35] opened 2017-04-25 16:50 UTC
Hi, Jeremy

 You have suggested to come back to older version of SLCIO (02.06). It appears I cannot compile slic for this older version. I've got this error:

``
 UTIL/LCStdHepRdrNew.h: No such file or directory
 #include "UTIL/LCStdHepRdrNew.h"
                                 ^
compilation terminated.
make[2]: *** [CMakeFiles/slic.dir/src/EventSourceManager.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/slic.dir/all] Error 2
make: *** [all] Error 2
``

I think it's better start fixing lcsim using the master version of LCIO

best, Sergei

**Comment by JeremyMcCormick** [comment] 2017-05-03 14:49
Perhaps we should move back to using `LCStdHepRdr` instead (though this would affect compatibility with certain StdHep files).  That would likely make it compatible with LCIO v02-06 but I agree that lcsim needs to be made compatible with the current LCIO release.

**Comment by JeremyMcCormick** [comment] 2017-05-05 04:07
Hi, Sergei.

Can you try out the `iss35` branch associated to this issue?  You should be able to get it with `git checkout origin/iss35`.  This version should be compatible with v02-06 of LCIO.  I have confirmed that this output is readable by lcsim.

It appears to me that the output from the 2.7 releases and greater cannot be read by lcsim due to incompatibilities, but this is a problem with the Java binding and not an issue with SLIC itself.

**Comment by JeremyMcCormick** [comment] 2017-05-05 12:38
This should be resolved by PR #37.

**Closed as completed by JeremyMcCormick** 2017-05-05 12:38 UTC
Labels: bug
